### ISSUE TITLE
Prompt for password in "mix firmware.push" when needed

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_firmware_ssh#4]
Currently, you need to pass the password in the cleartext on the commandline if you have one protecting your ssh private key. That's really not desirable. The current workaround is to tell people to run `upload.sh`. It would be so much better if `mix firmware.push` worked more like commandline ssh in this regard.

**Comment by JohnKacz** [comment]
Just a note for others looking here: until this issue is resolved you can use `read -s PASS_ENV_VAR` and then `mix firmware.push nerves.local --passphrase $PASS_ENV_VAR`

This at least keeps your passphrase out of your .*_history. Not knowing how firmware.push works completely I'm uncertain if there are other security implications to using this method in the interim.

**Comment by fhunleth** [comment]
Fwiw, I recommend using the upload shell script and avoid `mix firmware.push` unless you’re on Linux and don’t password protect your key. I’d really like the pure Erlang/Elixir way to work, but I keep finding little issues so I think it might be a while before that way works solidly. Help, obviously, would be appreciated since the script feels ugly.

**Comment by fhunleth** [comment]
Also, @johnkacz, thanks for posting the way to keep the password out of history. That’s useful.

**Comment by ConnorRigby** [comment]
This was resolved by #16 Can we close it?
